# Generated by Django 5.1.1 on 2024-09-19 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBase',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('studentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.studentbase')),
                ('course_name', models.IntegerField(choices=[(1, 'MCA'), (2, 'BCA'), (3, 'MBA'), (4, 'BBA'), (5, 'BSC IT')])),
            ],
            bases=('api.studentbase',),
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('studentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.studentbase')),
                ('hobby_name', models.CharField(max_length=20)),
            ],
            bases=('api.studentbase',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.studentbase')),
                ('name', models.CharField(max_length=16)),
                ('address', models.TextField(null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stream', to='api.courses')),
                ('hobbies', models.ManyToManyField(to='api.hobbies')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
            bases=('api.studentbase',),
        ),
    ]
